apiVersion: v1
kind: Pod
metadata:
  name: blake
  namespace: nnf-system
spec:
  restartPolicy: OnFailure
  containers:
    - name: blake
      image: alpine:latest
      env:
      - name: SCR_EXIT
        value: "1"
      command:
        - /bin/sh
        - -c
        - |
          echo "starting SCR..."
          sleep 10
          exit $SCR_EXIT